name: Build project

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-py-script:
    runs-on: ubuntu-20.04
    name: Build project
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup arm-none-eabi-gcc ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 10.3-2021.10
      - name: Install Cmake via PyPI
        run: python -m pip install cmake==3.28.3
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          python --version
      - name: Build default project using build.py
        run: python build.py
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: build-py-${{ matrix.os }}
          path: MICROBIT.hex
